server:
  port: 9001
  servlet:
    context-path: /api

spring:
  application:
    name: video-auth
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    
  # 邮件服务配置
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
      config:
        server-addr: localhost:8848
        file-extension: yaml

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.video.auth.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  secret: your-jwt-secret-key
  access-token-expire: 7200  # 访问令牌过期时间（秒）
  refresh-token-expire: 604800  # 刷新令牌过期时间（秒）

# OAuth配置
oauth:
  clients:
    github:
      client-id: your-github-client-id
      client-secret: your-github-client-secret
      authorize-url: https://github.com/login/oauth/authorize
      token-url: https://github.com/login/oauth/access_token
      user-info-url: https://api.github.com/user
      redirect-uri: http://localhost:8080/auth/oauth/github/callback
      scope: user:email
      
    google:
      client-id: your-google-client-id
      client-secret: your-google-client-secret
      authorize-url: https://accounts.google.com/o/oauth2/v2/auth
      token-url: https://oauth2.googleapis.com/token
      user-info-url: https://www.googleapis.com/oauth2/v3/userinfo
      redirect-uri: http://localhost:8080/auth/oauth/google/callback
      scope: profile email
      
    wechat:
      client-id: your-wechat-app-id
      client-secret: your-wechat-app-secret
      authorize-url: https://open.weixin.qq.com/connect/qrconnect
      token-url: https://api.weixin.qq.com/sns/oauth2/access_token
      user-info-url: https://api.weixin.qq.com/sns/userinfo
      redirect-uri: http://localhost:8080/auth/oauth/wechat/callback
      scope: snsapi_login

# 日志配置
logging:
  level:
    root: info
    com.video: debug
  file:
    name: logs/video-auth.log 